version: 2.1

orbs:
  maven: circleci/maven@1.0.3

jobs:
  build:
    executor: 
      name: maven/default
    steps:
      - checkout
      - maven/with_cache:
          steps:
            - run: mvn test
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit